### ISSUE TITLE
Make a SSO auth middleware to integrate Casdoor with Django

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/django-auth-sso#1]
Now we already have the Python SDK: https://github.com/casdoor/casdoor-python-sdk and the plugin for a popular Python open source software, Odoo: https://github.com/casdoor/odoo-casdoor-oauth

Now we need to develop the plugins for Django. This plugin ideally will be based on casdoor-python-sdk and will provide friendly interface for Django users, like a Django app can easily integrate with Casdoor login with only one or a few lines of code.

**Comment by hsluoyz** [comment]
@FitzLong

**Comment by CavalierSpirit** [comment]
How is this project going, looking forward to its release

**Comment by hsluoyz** [comment]
@leo220yuyaodog
